[package]
name = "pacman-mirrors"
version = "0.1.0"
authors = ["zentauro <pedrogomezmartin1999@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = "0.9.20"

[lib]
name = "pacman_mirrors_lib"
path = "src/lib.rs"

[[bin]]
name = "pacman-mirrors"
path = "src/main.rs"
